### ISSUE TITLE
Script fails as is when executed with a cron job

### ISSUE THREAD

**Issue by thomasmery** [wdhif/meteor-script-backup#2]
Hi,

this is is more of a question actually, I though you might help

I found that I had to remove the `t` option from the `docker run -it ...` line for the script to execute properly when launched via cron

otherwise I get a `cannot enable tty mode on non tty input` error in the logs
and the dup is not performed as far as I can tell

have you encountered the same issue?

not a big deal since just using `-i` seems to solve the issue but I thought I'd ask since I'm pretty new to docker (among other things :)

thanks

thomas

**Comment by wdhif** [comment]
Hi, 

Even if I get this error, the dump is still performed correctly for me.
But I will remove the -it from my command as we don't need an interactive TTY for the cron.

Thanks for the feedback

**Comment by thomasmery** [comment]
thanks for your answer,

and thanks again for the script
helped a lot

thomas
